activities = [
    {'activity': 'Opening the mail', 'risk': 'low', 'factor': 1},
    {'activity': 'Getting takeout', 'risk': 'low', 'factor': 2},
    {'activity': 'Going camping', 'risk': 'low', 'factor': 2},
    {'activity': 'Grocery shopping', 'risk': 'moderate-low', 'factor': 3},
    {'activity': 'Going for a run', 'risk': 'moderate-low', 'factor': 3},
    {'activity': 'Going for a bike ride', 'risk': 'moderate-low', 'factor': 3},
    {'activity': 'Going for a walk', 'risk': 'moderate-low', 'factor': 3},
    {'activity': 'Staying at a hotel', 'risk': 'moderate-low', 'factor': 4},
    {'activity': 'Going to the doctors', 'risk': 'moderate-low', 'factor': 4},
    {'activity': 'Eating at a patio', 'risk': 'moderate-low', 'factor': 4},
    {'activity': 'Walking in a busy area', 'risk': 'moderate-low', 'factor': 4},
    {'activity': 'Going to the playground', 'risk': 'moderate-low', 'factor': 4},
    {'activity': 'Hanging out with friends outside', 'risk': 'moderate', 'factor': 5},
    {'activity': 'Having dinner at a friends place', 'risk': 'moderate', 'factor': 5},
    {'activity': 'Going to a backyard bbq', 'risk': 'moderate', 'factor': 5},
    {'activity': 'Going to the shopping mall', 'risk': 'moderate', 'factor': 5},
    {'activity': 'Going to the beach', 'risk': 'moderate', 'factor': 5},
    {'activity': 'Sending kids to school, camp or daycare', 'risk': 'moderate', 'factor': 6},
    {'activity': 'Going to work at the office', 'risk': 'moderate', 'factor': 6},
    {'activity': 'Swimming in a public pool', 'risk': 'moderate', 'factor': 6},
    {'activity': 'Visiting an elderly friend/relative', 'risk': 'moderate', 'factor': 6},
    {'activity': 'Eating inside a restaurant', 'risk': 'moderate high', 'factor': 7},
    {'activity': 'Attending a wedding/funeral', 'risk': 'moderate high', 'factor': 7},
    {'activity': 'Playing team sports', 'risk': 'moderate high', 'factor': 7},
    {'activity': 'Hugging your friends', 'risk': 'moderate high', 'factor': 7},
    {'activity': 'Hanging out with friends inside', 'risk': 'moderate high', 'factor': 7},
    {'activity': 'Going to the salon or barber', 'risk': 'high', 'factor': 8},
    {'activity': 'Traveling by plane', 'risk': 'high', 'factor': 8},
    {'activity': 'Eating at a buffet', 'risk': 'high', 'factor': 8},
    {'activity': 'Working out at the gym', 'risk': 'high', 'factor': 8},
    {'activity': 'Going to a movie theatre', 'risk': 'high', 'factor': 8},
    {'activity': 'Going to a music concert', 'risk': 'high', 'factor': 9},
    {'activity': 'Attending a protest', 'risk': 'high', 'factor': 9},
    {'activity': 'Going to a sports stadium', 'risk': 'high', 'factor': 9},
    {'activity': 'Going to a bar', 'risk': 'high', 'factor': 9},
]