activities = [
    {'activity': 'opening the mail', 'risk': 'low', 'risk factor': 1},
    {'activity': 'getting takeout', 'risk': 'low', 'risk factor': 2},
    {'activity': 'going camping', 'risk': 'low', 'risk factor': 2},
    {'activity': 'grocery shopping', 'risk': 'moderate-low', 'risk factor': 3},
    {'activity': 'going for a run', 'risk': 'moderate-low', 'risk factor': 3},
    {'activity': 'going for a bike ride', 'risk': 'moderate-low', 'risk factor': 3},
    {'activity': 'going for a walk', 'risk': 'moderate-low', 'risk factor': 3},
    {'activity': 'staying at a hotel', 'risk': 'moderate-low', 'risk factor': 4},
    {'activity': 'going to the doctors', 'risk': 'moderate-low', 'risk factor': 4},
    {'activity': 'eating at a patio', 'risk': 'moderate-low', 'risk factor': 4},
    {'activity': 'walking in a busy area', 'risk': 'moderate-low', 'risk factor': 4},
    {'activity': 'going to the playground', 'risk': 'moderate-low', 'risk factor': 4},
    {'activity': 'hanging out with friends outside', 'risk': 'moderate', 'risk factor': 5},
    {'activity': 'having dinner at a friends place', 'risk': 'moderate', 'risk factor': 5},
    {'activity': 'going to a backyard bbq', 'risk': 'moderate', 'risk factor': 5},
    {'activity': 'going to the shopping mall', 'risk': 'moderate', 'risk factor': 5},
    {'activity': 'going to the beach', 'risk': 'moderate', 'risk factor': 5},
    {'activity': 'sending kids to school, camp or daycare', 'risk': 'moderate', 'risk factor': 6},
    {'activity': 'going to work at the office', 'risk': 'moderate', 'risk factor': 6},
    {'activity': 'swimming in a public pool', 'risk': 'moderate', 'risk factor': 6},
    {'activity': 'visiting an elderly friend/relative', 'risk': 'moderate', 'risk factor': 6},
    {'activity': 'eating inside a restaurant', 'risk': 'moderate high', 'risk factor': 7},
    {'activity': 'attending a wedding/funeral', 'risk': 'moderate high', 'risk factor': 7},
    {'activity': 'playing team sports', 'risk': 'moderate high', 'risk factor': 7},
    {'activity': 'hugging your friends', 'risk': 'moderate high', 'risk factor': 7},
    {'activity': 'hanging out with friends inside', 'risk': 'moderate high', 'risk factor': 7},
    {'activity': 'going to the salon or barber', 'risk': 'high', 'risk factor': 8},
    {'activity': 'traveling by plane', 'risk': 'high', 'risk factor': 8},
    {'activity': 'eating at a buffet', 'risk': 'high', 'risk factor': 8},
    {'activity': 'working out at the gym', 'risk': 'high', 'risk factor': 8},
    {'activity': 'going to a movie theatre', 'risk': 'high', 'risk factor': 8},
    {'activity': 'going to a music concert', 'risk': 'high', 'risk factor': 9},
    {'activity': 'attending a protest', 'risk': 'high', 'risk factor': 9},
    {'activity': 'going to a sports stadium', 'risk': 'high', 'risk factor': 9},
    {'activity': 'going to a bar', 'risk': 'high', 'risk factor': 9},
]