# Generated by Django 3.0.6 on 2020-07-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='distancing',
            field=models.BooleanField(default=False),
        ),
    ]
