# Generated by Django 3.0.6 on 2020-07-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200708_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='risk_level',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
