# Generated by Django 3.0.6 on 2020-07-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_activity_distancing'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='risk_level',
            field=models.IntegerField(default=0),
        ),
    ]
