# Generated by Django 3.0.6 on 2020-07-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200708_1907'),
        ('main_app', '0003_activity_risk_level'),
    ]

    operations = [
    ]
