# Generated by Django 3.0.6 on 2020-07-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_merge_20200708_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='activity',
            name='risk_level',
            field=models.IntegerField(default=0),
        ),
    ]
