# Generated by Django 3.0.6 on 2020-07-07 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='routine',
            field=models.ManyToManyField(to='main_app.Routine'),
        ),
        migrations.AddField(
            model_name='profile',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routine',
            name='name',
            field=models.CharField(default='first', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
