# Generated by Django 3.0.6 on 2020-07-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200707_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activity',
        ),
        migrations.AddField(
            model_name='profile',
            name='activity',
            field=models.ManyToManyField(to='main_app.Activity'),
        ),
    ]
