# Generated by Django 3.0.6 on 2020-07-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200709_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='user',
        ),
    ]
