# Generated by Django 3.0.6 on 2020-07-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200709_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distancing',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
