# Generated by Django 3.0.6 on 2020-07-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200709_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='activity_name',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
    ]
